# Generated by Django 5.1.3 on 2024-12-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crud',
            old_name='address',
            new_name='saddress',
        ),
        migrations.RenameField(
            model_name='crud',
            old_name='course',
            new_name='scourse',
        ),
        migrations.RenameField(
            model_name='crud',
            old_name='name',
            new_name='sname',
        ),
        migrations.RenameField(
            model_name='crud',
            old_name='roll_no',
            new_name='sroll_no',
        ),
    ]
