# Generated by Django 5.1.3 on 2024-12-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_rename_address_crud_saddress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crud',
            old_name='saddress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='crud',
            old_name='scourse',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='crud',
            old_name='sname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='crud',
            old_name='sroll_no',
            new_name='roll_no',
        ),
    ]
